# Generated by Django 5.0.2 on 2024-02-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_region', models.CharField(max_length=255)),
                ('libelle_region', models.CharField(max_length=255)),
                ('code_departement', models.CharField(max_length=255)),
                ('libelle_departement', models.CharField(max_length=255)),
                ('date_fin_semaine', models.DateField()),
                ('type_de_vaccin', models.CharField(max_length=255)),
                ('nb_ucd', models.CharField(max_length=255)),
                ('nb_doses', models.CharField(max_length=255)),
            ],
        ),
    ]
