# Generated by Django 5.0.2 on 2024-03-03 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='D_DATE',
            fields=[
                ('date_fin_semaine', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='D_LOCATION',
            fields=[
                ('code_region_code_departement', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('code_region', models.IntegerField()),
                ('code_departement', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('libelle_region', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('libelle_departement', models.CharField(blank=True, default=None, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='D_TYPE_VACCIN',
            fields=[
                ('vaccinlabel', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Flux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_region', models.CharField(max_length=255)),
                ('libelle_region', models.CharField(max_length=255)),
                ('code_departement', models.CharField(max_length=255)),
                ('libelle_departement', models.CharField(max_length=255)),
                ('date_fin_semaine', models.DateField()),
                ('type_de_vaccin', models.CharField(max_length=255)),
                ('nb_ucd', models.CharField(max_length=255)),
                ('nb_doses', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='F_FLUX',
            fields=[
                ('PK_F_FLUX', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nb_ucd', models.FloatField(blank=True, default=None, null=True)),
                ('nb_doses', models.FloatField(blank=True, default=None, null=True)),
                ('D_DATE', models.ForeignKey(db_column='D_DATE', on_delete=django.db.models.deletion.CASCADE, to='app.d_date')),
                ('D_LOCATION', models.ForeignKey(db_column='D_LOCATION', on_delete=django.db.models.deletion.CASCADE, to='app.d_location')),
                ('D_TYPE_VACCIN', models.ForeignKey(db_column='D_TYPE_VACCIN', on_delete=django.db.models.deletion.CASCADE, to='app.d_type_vaccin')),
            ],
            options={
                'unique_together': {('PK_F_FLUX', 'D_TYPE_VACCIN', 'D_DATE', 'D_LOCATION')},
            },
        ),
    ]
