# Generated by Django 5.0.2 on 2024-02-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='D_TYPE_VACCIN',
            fields=[
                ('vaccinlabel', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
    ]
