# Generated by Django 5.0.2 on 2024-03-03 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='f_flux',
            unique_together=set(),
        ),
    ]
