# Generated by Django 5.0.2 on 2024-02-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_d_type_vaccin'),
    ]

    operations = [
        migrations.CreateModel(
            name='D_DATE',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
    ]
