# Generated by Django 5.0.2 on 2024-02-25 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_nom_departement_d_location_libelle_departement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d_location',
            name='code_departement',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
        migrations.CreateModel(
            name='F_FLUX',
            fields=[
                ('PK_F_FLUX', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nb_ucd', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('nb_doses', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('D_DATE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_date')),
                ('D_LOCATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_location')),
                ('D_TYPE_VACCIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_type_vaccin')),
            ],
            options={
                'unique_together': {('PK_F_FLUX', 'D_TYPE_VACCIN', 'D_DATE', 'D_LOCATION')},
            },
        ),
    ]
