# Generated by Django 5.0.2 on 2024-02-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_d_location_code_departement_f_flux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f_flux',
            name='nb_doses',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='f_flux',
            name='nb_ucd',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
