# Generated by Django 5.0.2 on 2024-02-25 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_f_flux_nb_doses_alter_f_flux_nb_ucd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='d_date',
            old_name='date',
            new_name='date_fin_semaine',
        ),
    ]
