# Generated by Django 5.0.2 on 2024-02-25 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_date_d_date_date_fin_semaine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='d_type_vaccin',
            old_name='vaccinlabel',
            new_name='type_de_vaccin',
        ),
    ]
