# Generated by Django 5.0.2 on 2024-02-25 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_vaccinlabel_d_type_vaccin_type_de_vaccin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='d_type_vaccin',
            old_name='type_de_vaccin',
            new_name='vaccinlabel',
        ),
    ]
